#!/usr/bin/env python3
"""Render an unpublished Homebrew tap from verified flat release assets."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

COMPONENTS = {
    "flere": ("Flere", "Terminal workbench with persistent project sessions"),
    "flere-connect": ("Flere Connect", "SSH companion for the Flere terminal workbench"),
}
TARGETS = ("aarch64-apple-darwin", "x86_64-unknown-linux-gnu")
REPOSITORY = "https://github.com/robert-cronin/flere"
GLIBC_CHECK = '''set -eu
libc=$(/usr/bin/getconf GNU_LIBC_VERSION 2>/dev/null) || libc=unknown
case "$libc" in
  "glibc "*) version=${libc#glibc } ;;
  *) echo "Flere requires system glibc 2.39 or newer." >&2; exit 1 ;;
esac
case "$version" in
  *.*) ;;
  *) echo "Cannot read the system glibc version." >&2; exit 1 ;;
esac
major=${version%%.*}
minor=${version#*.}
case "$major:$minor" in
  *[!0-9:]*|:*|*:) echo "Cannot read the system glibc version." >&2; exit 1 ;;
esac
if [ "$major" -lt 2 ] || { [ "$major" -eq 2 ] && [ "$minor" -lt 39 ]; }; then
  echo "Flere requires system glibc 2.39 or newer (found $version)." >&2
  exit 1
fi
'''


def digest(path):
    checksum = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(65536), b""):
            checksum.update(chunk)
    return checksum.hexdigest()


def release_inputs(directory):
    """Validate all four payloads before changing any cask."""
    manifests = {}
    identities = set()
    for component in COMPONENTS:
        for target in TARGETS:
            name = f"{component}-{target}"
            path = directory / f"{name}.manifest.json"
            if path.is_symlink() or not path.is_file() or path.stat().st_size > 65536:
                raise ValueError(f"invalid manifest: {name}")
            manifest = json.loads(path.read_bytes())
            build, payload = manifest["build"], manifest["payload"]
            version = build["package_version"]
            source = manifest["source"]["source_sha256"]
            checksum = payload["sha256"]
            if (manifest["schema_version"] != 1 or build["component"] != component or
                    build["target"] != target or build["profile"] != "release" or
                    payload["file_name"] != component or payload["download_file"] != name):
                raise ValueError(f"unexpected release identity: {name}")
            if (not isinstance(version, str) or
                    not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version) or
                    not isinstance(source, str) or not re.fullmatch(r"[a-f0-9]{64}", source) or
                    not isinstance(checksum, str) or not re.fullmatch(r"[a-f0-9]{64}", checksum)):
                raise ValueError(f"invalid release version or checksum: {name}")
            binary = directory / name
            if (binary.is_symlink() or not binary.is_file() or
                    not isinstance(payload["bytes"], int) or
                    not 0 < payload["bytes"] <= 256 * 1024 * 1024 or
                    binary.stat().st_size != payload["bytes"] or digest(binary) != checksum):
                raise ValueError(f"payload differs from manifest: {name}")
            identities.add((version, source))
            manifests[component, target] = manifest
    if len(identities) != 1:
        raise ValueError("all casks need the same release version and source SHA-256")
    return manifests


def render(component, manifests):
    macos, linux = (manifests[component, target] for target in TARGETS)
    name, description = COMPONENTS[component]
    version = macos["build"]["package_version"]
    checks = "\n".join("        " + line for line in GLIBC_CHECK.rstrip().splitlines())
    return f'''# Generated by render.py from verified release manifests. Do not edit checksums by hand.
cask "{component}" do
  version "{version}"

  on_macos do
    sha256 "{macos['payload']['sha256']}"

    url "{REPOSITORY}/releases/download/v#{{version}}/{component}-aarch64-apple-darwin"

    depends_on macos: :big_sur
    depends_on arch: :arm64

    binary "{component}-aarch64-apple-darwin", target: "{component}"
  end
  on_linux do
    sha256 "{linux['payload']['sha256']}"

    url "{REPOSITORY}/releases/download/v#{{version}}/{component}-x86_64-unknown-linux-gnu"

    depends_on arch: :x86_64

    binary "{component}-x86_64-unknown-linux-gnu", target: "{component}"

    preflight_steps do
      write_file ".flere-check-glibc.sh", <<~SH
{checks}
      SH
      run "/bin/sh", args: ["{{{{staged_path}}}}/.flere-check-glibc.sh"]
    end
  end

  name "{name}"
  desc "{description}"
  homepage "{REPOSITORY}"

  container type: :naked

  caveats <<~EOS
    Update with: brew update && brew upgrade --cask robert-cronin/flere/{component}
    In-app Update manages a separate ~/.local/bin installation; use Homebrew here.
    Linux requires system glibc 2.39+. Linux ARM and Intel Macs are not packaged.
    macOS binaries are not Developer ID signed or notarized. Older macOS runtime
    acceptance remains pending; see the Flere release notes.
    Upgrades and uninstall preserve Flere state and do not stop running sessions.
  EOS
end
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("release_assets", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).parent)
    parser.add_argument("--check", action="store_true", help="verify recipes without writing")
    args = parser.parse_args()
    manifests = release_inputs(args.release_assets)
    recipes = {component: render(component, manifests) for component in COMPONENTS}
    if args.check:
        for component, recipe in recipes.items():
            path = args.output / "Casks" / f"{component}.rb"
            if path.read_text() != recipe:
                raise ValueError(f"recipe does not match release assets: {component}")
        print("Homebrew recipes match all four verified release payloads.")
    else:
        output = args.output / "Casks"
        output.mkdir(parents=True, exist_ok=True)
        for component, recipe in recipes.items():
            (output / f"{component}.rb").write_text(recipe)
        print("Prepared two Homebrew casks; nothing published or installed.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Homebrew preparation stopped: {error}", file=sys.stderr)
        sys.exit(1)
