# Generated by render.py from verified release manifests. Do not edit checksums by hand.
cask "flere-connect" do
  version "0.3.0"

  on_macos do
    sha256 "c46102b3c64205964be98c7732496ab1aed7965631a9e20156dd4496cbbd1e3c"

    url "https://github.com/robert-cronin/flere/releases/download/v#{version}/flere-connect-aarch64-apple-darwin"

    depends_on macos: :big_sur
    depends_on arch: :arm64

    binary "flere-connect-aarch64-apple-darwin", target: "flere-connect"
  end
  on_linux do
    sha256 "967e7e7cf68e927c2810db66450be93f3fab13b0980b158561c583b473fe8fb6"

    url "https://github.com/robert-cronin/flere/releases/download/v#{version}/flere-connect-x86_64-unknown-linux-gnu"

    depends_on arch: :x86_64

    binary "flere-connect-x86_64-unknown-linux-gnu", target: "flere-connect"

    preflight_steps do
      write_file ".flere-check-glibc.sh", <<~SH
        set -eu
        libc=$(/usr/bin/getconf GNU_LIBC_VERSION 2>/dev/null) || libc=unknown
        case "$libc" in
          "glibc "*) version=${libc#glibc } ;;
          *) echo "Flere requires system glibc 2.39 or newer." >&2; exit 1 ;;
        esac
        case "$version" in
          *.*) ;;
          *) echo "Cannot read the system glibc version." >&2; exit 1 ;;
        esac
        major=${version%%.*}
        minor=${version#*.}
        case "$major:$minor" in
          *[!0-9:]*|:*|*:) echo "Cannot read the system glibc version." >&2; exit 1 ;;
        esac
        if [ "$major" -lt 2 ] || { [ "$major" -eq 2 ] && [ "$minor" -lt 39 ]; }; then
          echo "Flere requires system glibc 2.39 or newer (found $version)." >&2
          exit 1
        fi
      SH
      run "/bin/sh", args: ["{{staged_path}}/.flere-check-glibc.sh"]
    end
  end

  name "Flere Connect"
  desc "SSH companion for the Flere terminal workbench"
  homepage "https://github.com/robert-cronin/flere"

  container type: :naked

  caveats <<~EOS
    Update with: brew update && brew upgrade --cask robert-cronin/flere/flere-connect
    In-app Update manages a separate ~/.local/bin installation; use Homebrew here.
    Linux requires system glibc 2.39+. Linux ARM and Intel Macs are not packaged.
    macOS binaries are not Developer ID signed or notarized. Older macOS runtime
    acceptance remains pending; see the Flere release notes.
    Upgrades and uninstall preserve Flere state and do not stop running sessions.
  EOS
end
