# Generated by render.py from verified release manifests. Do not edit checksums by hand.
cask "flere" do
  version "0.3.0"

  on_macos do
    sha256 "fc1111761729e994adac5d9aadd00948facd50c46d7f5eaa6ea35ee7ba32e6b1"

    url "https://github.com/robert-cronin/flere/releases/download/v#{version}/flere-aarch64-apple-darwin"

    depends_on macos: :big_sur
    depends_on arch: :arm64

    binary "flere-aarch64-apple-darwin", target: "flere"
  end
  on_linux do
    sha256 "3ad4f2597e41a853a694c2f0480de0e850b85cf5d2913271685c2b503472ad8b"

    url "https://github.com/robert-cronin/flere/releases/download/v#{version}/flere-x86_64-unknown-linux-gnu"

    depends_on arch: :x86_64

    binary "flere-x86_64-unknown-linux-gnu", target: "flere"

    preflight_steps do
      write_file ".flere-check-glibc.sh", <<~SH
        set -eu
        libc=$(/usr/bin/getconf GNU_LIBC_VERSION 2>/dev/null) || libc=unknown
        case "$libc" in
          "glibc "*) version=${libc#glibc } ;;
          *) echo "Flere requires system glibc 2.39 or newer." >&2; exit 1 ;;
        esac
        case "$version" in
          *.*) ;;
          *) echo "Cannot read the system glibc version." >&2; exit 1 ;;
        esac
        major=${version%%.*}
        minor=${version#*.}
        case "$major:$minor" in
          *[!0-9:]*|:*|*:) echo "Cannot read the system glibc version." >&2; exit 1 ;;
        esac
        if [ "$major" -lt 2 ] || { [ "$major" -eq 2 ] && [ "$minor" -lt 39 ]; }; then
          echo "Flere requires system glibc 2.39 or newer (found $version)." >&2
          exit 1
        fi
      SH
      run "/bin/sh", args: ["{{staged_path}}/.flere-check-glibc.sh"]
    end
  end

  name "Flere"
  desc "Terminal workbench with persistent project sessions"
  homepage "https://github.com/robert-cronin/flere"

  container type: :naked

  caveats <<~EOS
    Update with: brew update && brew upgrade --cask robert-cronin/flere/flere
    In-app Update manages a separate ~/.local/bin installation; use Homebrew here.
    Linux requires system glibc 2.39+. Linux ARM and Intel Macs are not packaged.
    macOS binaries are not Developer ID signed or notarized. Older macOS runtime
    acceptance remains pending; see the Flere release notes.
    Upgrades and uninstall preserve Flere state and do not stop running sessions.
  EOS
end
