# Generated by scripts/linux-packages.py from the reviewed release lock.
# This upstream prebuilt wrapper preserves the published payload bytes.
%global debug_package %{nil}
%global __brp_strip %{nil}
%global __brp_strip_comment_note %{nil}
%global _build_id_links none

Name:           flere
Version:        0.3.0
Release:        1
Summary:        Terminal workbench with a custom UI and SSH companion
License:        MIT AND OFL-1.1
URL:            https://github.com/robert-cronin/flere
ExclusiveArch:  x86_64
BuildRequires:  coreutils
Requires:       glibc%{?_isa} >= 2.39
Requires:       libgcc%{?_isa}
Requires:       libz.so.1()(64bit)
Requires:       git-core
Recommends:     openssh-clients
Suggests:       vim-enhanced
Suggests:       wayland-libs
Provides:       flere-connect = %{version}-%{release}
Conflicts:      flere-connect
Source0:        https://github.com/robert-cronin/flere/releases/download/v0.3.0/flere-x86_64-unknown-linux-gnu
Source1:        https://github.com/robert-cronin/flere/releases/download/v0.3.0/flere-x86_64-unknown-linux-gnu.manifest.json
Source2:        https://github.com/robert-cronin/flere/releases/download/v0.3.0/flere-connect-x86_64-unknown-linux-gnu
Source3:        https://github.com/robert-cronin/flere/releases/download/v0.3.0/flere-connect-x86_64-unknown-linux-gnu.manifest.json
Source4:        https://raw.githubusercontent.com/robert-cronin/flere/3959a33af47123c11a33cf7ff62ac9695c49a9dd/LICENSE
Source5:        https://raw.githubusercontent.com/robert-cronin/flere/3959a33af47123c11a33cf7ff62ac9695c49a9dd/src/assets/fonts/OFL.txt
Source6:        https://raw.githubusercontent.com/robert-cronin/flere/3959a33af47123c11a33cf7ff62ac9695c49a9dd/src/assets/fonts/LICENSE-Nerd-Fonts

%description
Flere provides a custom terminal UI for project workspaces and peer agents.
Includes the SSH companion. Native shells, editors and agents remain external.
This prebuilt x86-64 release requires glibc 2.39 or newer. Installation and
removal start no supervisor, shell or native chat.

%prep
cd '%{_sourcedir}'
sha256sum --check <<'FLERE_SHA256'
3ad4f2597e41a853a694c2f0480de0e850b85cf5d2913271685c2b503472ad8b  flere-x86_64-unknown-linux-gnu
52cf877d56d0f4fec6db7a1f6b9d1df623c9483908ed22fa16aaba2e40975574  flere-x86_64-unknown-linux-gnu.manifest.json
967e7e7cf68e927c2810db66450be93f3fab13b0980b158561c583b473fe8fb6  flere-connect-x86_64-unknown-linux-gnu
25a3e5c91db265b251225d4ec08becf5243c5829e6e350cac708bec9e612815f  flere-connect-x86_64-unknown-linux-gnu.manifest.json
b997b4ab95fef146345de8b279c4d6dff41fc4a198d2bfe2488ba0ae0ac071d5  LICENSE
60d55f23c6ce05a81099a762cb67ca2c9b6ea251c7912720998b4c89ebfd4faa  OFL.txt
bede0739eb2bf948765623a7a134360a6320240f4a9e29a5a68f31e191b0f8d0  LICENSE-Nerd-Fonts
FLERE_SHA256

%build
# The reviewed executables are packaged without recompilation.

%install
install -Dm755 '%{SOURCE0}' '%{buildroot}%{_bindir}/flere'
install -Dm644 '%{SOURCE1}' '%{buildroot}%{_datadir}/flere/flere.manifest.json'
install -Dm755 '%{SOURCE2}' '%{buildroot}%{_bindir}/flere-connect'
install -Dm644 '%{SOURCE3}' '%{buildroot}%{_datadir}/flere/flere-connect.manifest.json'
install -Dm644 '%{SOURCE4}' '%{buildroot}%{_licensedir}/%{name}/LICENSE'
install -Dm644 '%{SOURCE5}' '%{buildroot}%{_licensedir}/%{name}/OFL.txt'
install -Dm644 '%{SOURCE6}' '%{buildroot}%{_licensedir}/%{name}/LICENSE-Nerd-Fonts'

%check
# Check bytes without executing either prebuilt program.
cmp '%{SOURCE0}' '%{buildroot}%{_bindir}/flere'
cmp '%{SOURCE1}' '%{buildroot}%{_datadir}/flere/flere.manifest.json'
cmp '%{SOURCE2}' '%{buildroot}%{_bindir}/flere-connect'
cmp '%{SOURCE3}' '%{buildroot}%{_datadir}/flere/flere-connect.manifest.json'
cmp '%{SOURCE4}' '%{buildroot}%{_licensedir}/%{name}/LICENSE'
cmp '%{SOURCE5}' '%{buildroot}%{_licensedir}/%{name}/OFL.txt'
cmp '%{SOURCE6}' '%{buildroot}%{_licensedir}/%{name}/LICENSE-Nerd-Fonts'

%files
%defattr(-,root,root,-)
%dir %{_datadir}/flere
%dir %{_licensedir}/%{name}
%{_bindir}/flere
%{_datadir}/flere/flere.manifest.json
%{_bindir}/flere-connect
%{_datadir}/flere/flere-connect.manifest.json
%license %{_licensedir}/%{name}/LICENSE
%license %{_licensedir}/%{name}/OFL.txt
%license %{_licensedir}/%{name}/LICENSE-Nerd-Fonts
